main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
api-version: 1.21
folia-supported: true
name: CoinsEngine
author: NightExpress
desciption: Unlimited virtual currencies and server economy.
load: STARTUP
dependencies:
  server:
    nightcore:
      load: BEFORE
      required: true
    Vault:
      required: false
    PlaceholderAPI:
      required: false
    PlayerPoints:
      required: false
    DeluxeCoinflip:
      required: false