main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
name: CoinsEngine
author: NightExpress
desciption: Unlimited virtual currencies with Vault Economy support!
depend: [ nightcore ]
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - DeluxeCoinflip
load: STARTUP
api-version: 1.19